import React from 'react'

const Profile = () => {
  return (
    <div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex nulla ullam perspiciatis rerum cum tempore ea, dolor obcaecati illum assumenda iure unde eum laboriosam animi suscipit maxime! Ut qui fuga dicta magnam similique, ab facere error, excepturi sequi doloribus explicabo asperiores quod? Laboriosam alias veritatis itaque. Itaque laudantium dolorum earum nisi illum corporis minima, laboriosam et cumque sed ipsam in dignissimos saepe accusamus repellendus nostrum aliquid veniam fugiat sit adipisci? Dolore iure dolorum quae eius minus asperiores voluptatibus sunt fuga libero ipsa. Quam omnis nam obcaecati dicta facilis id quaerat. Atque aliquid consequuntur architecto odio quo eum corporis dignissimos, nemo veniam dolorum eos obcaecati? Animi quia iste pariatur ducimus. Perferendis quaerat incidunt delectus ratione nulla error, voluptatem modi rerum, velit magnam reiciendis temporibus, voluptate eum. Eveniet enim ad nostrum repellendus officiis. Ipsa eum exercitationem commodi? Soluta, rem inventore quod nemo necessitatibus velit alias tenetur eaque facere similique, minus odit corrupti eligendi expedita! Amet voluptate natus illo expedita vero nemo repellat! Excepturi nisi, ipsam est eaque illo ratione vero facere pariatur quia ut quos voluptatem ipsum error totam. Nobis doloremque iste expedita adipisci rerum voluptatum doloribus ducimus at quidem distinctio? Odit velit quas ducimus. Harum, laboriosam? Quisquam exercitationem accusantium, numquam nesciunt veritatis minima laudantium tempore voluptate assumenda aliquam eligendi sit delectus dicta, qui ipsam, beatae esse ullam sed natus neque! Velit eaque, a autem incidunt et modi quod ipsam fugiat voluptatum quo unde quasi? Facere enim, esse eaque sed labore ut odio consequatur ad quisquam velit blanditiis nisi iste suscipit voluptatem. Laboriosam provident impedit modi, consectetur est illo quia accusantium dolores quaerat eos porro quibusdam eius maxime ullam, veritatis autem. Error, numquam amet enim atque ad, nulla ab fuga laborum recusandae reiciendis exercitationem maiores reprehenderit iure fugiat rerum voluptatum vitae at. Impedit neque laudantium velit laborum corporis dicta vitae sed.
    </div>
  )
}

export default Profile
