import React from 'react'

const Teams = () => {
  return (
    <div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea nostrum culpa ut quam quas, eveniet consequuntur quia recusandae quis officiis doloremque sit cumque illum error. Atque illo, ducimus provident ipsam velit est, sed perferendis laborum reiciendis, porro molestias earum molestiae ipsa. Odit voluptas numquam vero nemo, corporis doloremque qui architecto odio nostrum error fugit. Facilis ipsam, ipsum cupiditate ducimus ipsa ad quae vitae ratione nobis eius fuga, eum ab ex possimus optio impedit. Libero vitae id repellat odit, cupiditate rem illum culpa exercitationem quod delectus corrupti! Dignissimos atque corporis odio! Illo perspiciatis similique laudantium veritatis iure vero qui nobis facilis, ratione repellat excepturi fugiat officia ab repellendus dolores earum deleniti, dolorum optio nisi vel ea! Saepe voluptatibus aperiam natus tempore quasi magnam adipisci consequuntur aspernatur pariatur, omnis ad unde fugiat eaque, animi tenetur deserunt eligendi. Culpa dolorum itaque unde quae dolores velit fuga veniam praesentium quod molestias eligendi qui, sed aspernatur consequuntur aliquid voluptatibus, perspiciatis veritatis et! Est, illo? Voluptatum tempore commodi optio perferendis ex laborum perspiciatis temporibus a iste eum similique expedita voluptatem dolor accusantium velit, nisi laudantium aperiam doloribus est minus? Sit eligendi quibusdam iusto laudantium unde doloribus illo nihil aliquid in labore mollitia, illum vitae sed error adipisci odit esse molestias perferendis dolorum voluptatum architecto? Quae culpa eligendi accusantium sed voluptatum fuga, id itaque iure omnis assumenda, reiciendis animi ipsam mollitia cumque nostrum! Reiciendis perspiciatis amet quibusdam, vel sunt alias ut placeat dolore ipsa aliquid tempore nostrum at consequuntur? Enim optio ea dolor blanditiis, obcaecati molestiae fuga quam amet vero. Reiciendis nihil assumenda nobis sunt quis! Minus sed consectetur corporis! Facilis inventore dolorum repellat aliquam velit deleniti vitae dolores recusandae. Voluptatum vero aliquam molestiae vitae optio, facere odio nulla quaerat earum cumque? Placeat at voluptate ullam eius corporis reiciendis magni quo provident ut officiis, magnam, neque ducimus.
    </div>
  )
}

export default Teams
